version: "3.8"
services:
  train:
    build: .
    shm_size: 16g
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /workspace
    command: bash